# Basic Setting
title: "Y.-L. Zheng"
name: "Yun-Liang Zheng"
email: 
url: 
keywords: 
description:
contact: static

# Footer
footer:
  credit: 'This website is based on Jekyll theme <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a>.'
  copyright: Y.-L. Zheng
  location: Shanghai
  
#
