baseurl: https://al-yl.github.io/
languageCode: zh-CN
theme: hugo-theme-stack
paginate: 5
title: Yunliang Zheng's Homepage

widgets:
    enabled:
        - search
        - archives
        - tag-cloud

permalinks:
    post: /p/:slug/
    page: /:slug/

menu:
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/al-YL
          params:
              icon: brand-github
    main:
        - identifier: cv
          name: About Me 
          url: https://docs.google.com/viewer?url=https://github.com/Al-YL/al-yl.github.io/raw/main/content/cv2021.pdf
          weight: -100
          params:
            icon: user
            newTab: true
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home
            newTab: true



params:
    mainSections:
        - posts
    sidebar: #左边栏
        emoji: ☕️
        subtitle: 个人科研仓库
        avatar:
            enabled: true
            local: true
            src: me.jpg
    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: false 
            default: Licensed under CC BY-NC-SA 4.0
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc
            - type: search
            - type: archives
              params:
                  limit: 5

